SELECT DISTINCT EMP.DEPTNO, DEPT.LOC
FROM EMP, DEPT;

SELECT DISTINCT DEPTNO
FROM EMP;

SELECT ENAME, DEPTNO
FROM EMP
ORDER BY ENAME;

SELECT *
FROM EMP
WHERE SAL >= 1000 AND DEPTNO = 20;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
HAVING JOB = 'MANAGER'
ORDER BY JOB;

SELECT *
FROM EMP
WHERE DEPTNO = 20 OR JOB = 'SALESMAN';

SELECT *
FROM EMP
WHERE NOT (JOB = 'MANAGER' OR JOB = 'SALESMAN' OR JOB = 'CLERK');

SELECT *
FROM EMP
WHERE JOB LIKE '%A%'; 

SELECT *
FROM EMP
WHERE COMM IS NULL; 

SELECT *
FROM EMP, DEPT
WHERE DEPT.Loc = 'NEW YORK' AND EMP.JOB = 'SALESMAN';