DESC EMP;
DESC DEPT;

-- 추가 수당 '해당 사항 없음', '추가 수당 없음', '추가 수당 xx'
SELECT ENAME,
CASE
WHEN COMM IS NULL THEN '해당 사항 없음'
WHEN COMM = 0 THEN '추가 수당 없음'
ELSE CONCAT('추가 수당 : ', TO_CHAR(COMM))
END AS COMM
FROM EMP;

SELECT EMPNO, ENAME,
CASE
WHEN COMM IS NULL THEN '해당 사항 없음'
WHEN COMM = 0 THEN '추가 수당 없음'
WHEN COMM > 0 THEN '추가 수당 : ' || COMM
END AS COMM
FROM EMP;

-- EMP 테이블과 DEPT 테이블에서 공통으로 있는 부서번호 출력
SELECT DEPTNO
FROM EMP
INTERSECT
SELECT DEPTNO
FROM DEPT;

-- 연도별 부서별 인원수
SELECT EXTRACT(YEAR FROM HIREDATE) AS HIREYEAR, DEPTNO, COUNT(*)
FROM EMP
GROUP BY GROUPING SETS((EXTRACT(YEAR FROM HIREDATE)), (DEPTNO), (EXTRACT(YEAR FROM HIREDATE), DEPTNO));

SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR, DEPTNO, COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO;



-- 각 부서별, 직업별, 그룹화된 부서 + 각 직업별, 전체 인원수, 급여 총액 (그룹화된 부서 : GROUP_DEPT, 그룹화된 직업 : GROUP_JOB)
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL), GROUPING(DEPTNO) AS GROUP_DEPT, GROUPING(JOB) AS GROUP_JOB
FROM EMP
GROUP BY GROUPING SETS((DEPTNO), (JOB), (DEPTNO, JOB));

SELECT DECODE(GROUPING(DEPTNO), 1, 'GTOUP_DEPT', DEPTNO) AS DEPTNO,
       DECODE(GROUPING(JOB), 1, 'GTOUP_JOB', JOB) AS JOB,
       COUNT(*), SUM(SAL)
FROM EMP
GROUP BY CUBE(DEPTNO, JOB)
ORDER BY DEPTNO, JOB;

SELECT 
CASE
WHEN GROUPING(DEPTNO) = 1 THEN 'GROUP_DEPT'
ELSE TO_CHAR(DEPTNO)
END AS DEPTNO,
CASE
WHEN GROUPING(JOB) = 1 THEN 'GROUP_JOB'
ELSE JOB
END AS JOB,
COUNT(*), SUM(SAL)
FROM EMP
GROUP BY GROUPING SETS((DEPTNO), (JOB), (DEPTNO, JOB))
ORDER BY DEPTNO, JOB;

--------------------------------------------------------------------------------

-- EMP 테이블과 DEPT 테이블에서 공통으로 있는 부서번호 출력 (간단하게 해결하는 방법)
SELECT DISTINCT EMP.DEPTNO
FROM EMP, DEPT
ORDER BY DEPT.DEPTNO, EMP.EMPNO;

SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
FROM EMP E
INNER JOIN DEPT ON E.DEPTNO = DEPT.DEPTNO
ORDER BY DEPT.DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
FROM EMP E
RIGHT OUTER JOIN DEPT ON E.DEPTNO = DEPT.DEPTNO
ORDER BY DEPT.DEPTNO, E.EMPNO;

SELECT E.ENAME, DEPT.DNAME
FROM EMP E
INNER JOIN DEPT ON E.DEPTNO = DEPT.DEPTNO
ORDER BY DEPT.DEPTNO, E.EMPNO;

SELECT *
FROM EMP;

-- EMP 테이블에서 자신의 상급자 이름을 더해서 출력
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.MGR, E2.ENAME AS MGR_NAME, E1.HIREDATE, E1.SAL, E1.COMM, E1.DEPTNO 
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

SELECT *
FROM SALGRADE;

-- SALGRADE 테이블의 SAL 등급을 반영해서 출력
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, S.GRADE AS SAL_GRADE, E.COMM, E.DEPTNO
FROM EMP E, SALGRADE S
WHERE E.SAL >= S.LOSAL AND E.SAL <= S.HISAL
ORDER BY E.EMPNO;

SELECT E.ENAME, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

--------------------------------------------------------------------------------
SELECT *
FROM EMP E
LEFT OUTER JOIN EMP ON E.MGR = EMP.EMPNO;

SELECT *
FROM EMP E1
RIGHT OUTER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

--------------------------------------------------------------------------------

SELECT *
FROM EMP E1
NATURAL JOIN EMP E2;

SELECT *
FROM EMP
NATURAL JOIN DEPT;

SELECT E.EMPNO, E.ENAME, E.MGR, DEPTNO, D.DNAME, D.LOC
FROM EMP E
NATURAL JOIN DEPT D;


SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
FROM EMP E
NATURAL JOIN DEPT D
ORDER BY DEPTNO, E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, DEPTNO, D.DNAME, D.LOC
FROM EMP E
JOIN DEPT D USING(DEPTNO)
ORDER BY DEPTNO, E.EMPNO;


-- SALGRADE - HISAL을 받는 사람의 인원 수를 등급별로 출력해보기
SELECT S.GRADE, COUNT(*) AS TOTAL_COUNT
FROM EMP E, SALGRADE S
WHERE E.SAL = S.HISAL
GROUP BY S.GRADE
ORDER BY S.GRADE;

SELECT S.GRADE,
CASE
WHEN COUNT(E.SAL) = 0 THEN 0
ELSE COUNT(E.SAL)
END AS TOTAL_COUNT
FROM SALGRADE S
LEFT OUTER JOIN EMP E ON E.SAL = S.HISAL
GROUP BY S.GRADE
ORDER BY S.GRADE;

-- EMP 테이블에서 DEPT 테이블과 공통된 'DEPT' 값을 가지지 않은 부서 이름과 위치를 출력해보기
SELECT DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
FROM DEPT
LEFT OUTER JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
WHERE EMP.DEPTNO IS NULL;

SELECT DEPT.DEPTNO, DEPT.DNAME, DEPT.LOC
FROM DEPT
FULL OUTER JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
WHERE DEPT.DEPTNO IS NULL OR EMP.DEPTNO IS NULL;

-- EMP와 DEPT 결합해서 JOB이 MANAGER인 애들 출력해보기
SELECT *
FROM EMP E
JOIN DEPT D USING(DEPTNO)
WHERE JOB = 'MANAGER'
ORDER BY E.EMPNO;

--------------------------------------------------------------------------------

-- 그룹별 최고 급여 직원 출력
SELECT MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT *
FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT *
FROM EMP
WHERE SAL = ANY(SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);

-- 30번 부서 사원들의 최대 급여보다 적은 급여를 받는 사람들 출력하기
SELECT *
FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30 GROUP BY DEPTNO);

SELECT *
FROM EMP
WHERE SAL < ANY(SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30);

SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E10, (SELECT * FROM DEPT) D
WHERE E10.DEPTNO = D.DEPTNO;

WITH E10 AS (SELECT * FROM EMP WHERE DEPTNO = 10), D AS (SELECT * FROM DEPT)
SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
FROM E10, D
WHERE E10.DEPTNO = D.DEPTNO;

-- EMP 테이블에서 가장 높은 급여를 받는 직원의 이름과 급여를 출력
SELECT ENAME, SAL 
FROM EMP
WHERE (SELECT MAX(SAL) FROM EMP) = SAL;

-- DEPT 테이블에서 각 부서별로 속한 직원의 수와 평균 급여를 출력
SELECT COUNT(*) FROM EMP GROUP BY DEPTNO;

SELECT ROUND(AVG(SAL)) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO,
    (SELECT COUNT(*) FROM EMP WHERE DEPT.DEPTNO = EMP.DEPTNO GROUP BY DEPTNO) AS EMP_COUNT,
    (SELECT ROUND(AVG(SAL)) FROM EMP WHERE DEPT.DEPTNO = EMP.DEPTNO GROUP BY DEPTNO) AS AVER_SAL
FROM DEPT;

-- EMP 테이블에서 직원의 급여가 부서 평균 급여보다 높은 경우에만 출력
SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;

WITH E1 AS(SELECT * FROM EMP), E2 AS (SELECT DEPTNO, ROUND(AVG(SAL)) AS AVG_SAL FROM EMP GROUP BY DEPTNO)
SELECT *
FROM E1
JOIN E2 ON E1.DEPTNO = E2.DEPTNO
WHERE E1.DEPTNO = E2.DEPTNO AND E1.SAL > E2.AVG_SAL;

SELECT ENAME, SAL
FROM EMP E1, (SELECT ROUND(AVG(SAL)) AS AVG_SAL, DEPTNO FROM EMP GROUP BY DEPTNO) E2
WHERE E1.SAL > E2.AVG_SAL AND E1.DEPTNO = E2.DEPTNO;

-- EMP 테이블에서 부서 번호가 10인 부서에 속한 직원들 중에서 급여가 3000 이상인 직원의 이름과 급여를 출력
SELECT E.ENAME, E.SAL
FROM (SELECT * FROM EMP WHERE DEPTNO = 10) E
WHERE E.SAL >= 3000;

SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO = 10 AND SAL >= 3000;

--------------------------------------------------------------------------------

--각 직원의 이름과 부서 이름을 출력. (부서 번호 대신 부서 이름)
--각 직원의 이름과 해당 직원의 급여를 조회하되, 급여가 부서 평균 급여보다 높은 경우에는 "상위"라고 표시하고 그 외에는 "일반"이라고 출력
--각 부서별로 속한 직원의 수와 평균 급여를 조회하되, 급여가 해당 부서의 평균 급여보다 높은 직원의 이름과 급여를 함께 출력(평균 급여 내림차순으로 정렬)
--각 직원의 이름과 보너스를 조회하되, 보너스가 없는 직원들 중에서 가장 급여가 높은 직원의 이름과 급여를 출력