# Generated by Django 4.2.5 on 2023-09-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20230919_1554'),
        ('newapp', '0003_auto_20230919_1615'),
    ]

    operations = [
    ]
